# Generated by Django 2.1.7 on 2020-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='difference_from_max',
            field=models.IntegerField(default=300),
        ),
    ]
